trigger:
  branches:
    include: ['main']

steps:
- task: ComponentGovernanceComponentDetection@0
  inputs:
    ignoreDirectories: 'containers,repository-containers,container-templates,script-library'
